version: '3'

services:
  frontend:
    image: chkalovec/time-app-frontend-dev
    ports:
      - '3333:3000'
    restart: always
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    image: chkalovec/time-app-api-dev
    ports:
      - '5555:5000'
    restart: always
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      MY_SQL_HOST: mysql
      MY_SQL_USER: root
      MY_SQL_PASSWORD: password
      MY_SQL_PORT: '3306'
      MY_SQL_DB: time_db
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - '8888:8080'
    restart: always

volumes:
  mysql_data:
